_defaults:
  tz: America/Chicago

sources:
  - name: "Vilas County (Modern Tribe)"
    kind: modern_tribe
    url: "https://vilaswi.com/events/?eventDisplay=list"
    snapshot_path: "state/snapshots/vilas_county_(modern_tribe).html"

  - name: "Boulder Junction (Modern Tribe)"
    kind: modern_tribe
    url: "https://boulderjct.org/events/?eventDisplay=list"
    snapshot_path: "state/snapshots/boulder_junction_(modern_tribe).html"

  - name: "Eagle River Chamber (Modern Tribe)"
    kind: modern_tribe
    url: "https://eagleriver.org/events/?eventDisplay=list"
    snapshot_path: "state/snapshots/eagle_river_chamber_(modern_tribe).html"

  - name: "Rhinelander Chamber (GrowthZone)"
    kind: growthzone
    url: "https://business.rhinelanderchamber.com/events/calendar"
    snapshot_path: "state/snapshots/rhinelander_chamber_(growthzone).html"

  - name: "Town of Arbor Vitae (Municipal Calendar)"
    kind: simpleview   # Squarespace/municipal-like; our Simpleview parser is tolerant
    url: "https://www.townofarborvitae.org/calendar/"
    snapshot_path: "state/snapshots/town_of_arbor_vitae_(municipal_calendar).html"

  - name: "Minocqua Area Chamber (Simpleview)"
    kind: simpleview
    url: "https://www.minocqua.org/events/"
    snapshot_path: "state/snapshots/minocqua_area_chamber_(modern_tribe).html"

  - name: "Oneida County – Festivals & Events (Simpleview)"
    kind: simpleview
    url: "https://oneidacountywi.com/festivals-events/"
    snapshot_path: "state/snapshots/oneida_county_-_festivals_and_events_(modern_tribe).html"

  - name: "St. Germain Chamber (Modern Tribe)"
    kind: modern_tribe
    url: "https://st-germain.com/events-calendar/?eventDisplay=list"
    snapshot_path: "state/snapshots/st._germain_chamber_(modern_tribe).html"

  - name: "Sayner–Star Lake–Cloverland Chamber (ICS)"
    kind: ics
    url: "https://sayner-starlake-cloverland.org/events/?ical=1"
