defaults:
  tz: America/Chicago

sources:
  - name: Vilas County (Modern Tribe)
    kind: modern_tribe
    url: https://vilaswi.com/events/?eventDisplay=list

  - name: Boulder Junction (Modern Tribe)
    kind: modern_tribe
    url: https://boulderjct.org/events/?eventDisplay=list

  - name: Oneida County – Festivals & Events (Modern Tribe)
    kind: modern_tribe
    url: https://oneidacountywi.com/festivals-events/?eventDisplay=list
    ics_url: https://oneidacountywi.com/festivals-events/?ical=1

  - name: Eagle River Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://eagleriver.org/events/?eventDisplay=list

  - name: Rhinelander Chamber (GrowthZone)
    kind: growthzone
    url: https://business.rhinelanderchamber.com/events/calendar

  - name: St. Germain Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    ics_url: https://st-germain.com/events-calendar/?ical=1

  - name: Minocqua Area Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://www.minocqua.org/events/?eventDisplay=list
    ics_url: https://www.minocqua.org/events/?ical=1

  - name: Town of Arbor Vitae (Municipal Calendar)
    kind: municipal
    url: https://www.townofarborvitae.org/calendar/
    ics_url: https://www.townofarborvitae.org/calendar/?ical=1

  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://sayner-starlake-cloverland.org/events/
    ics_url: https://sayner-starlake-cloverland.org/events/?ical=1

  - name: Manitowish Waters Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://manitowishwaters.org/events/?eventDisplay=list
    ics_url: https://manitowishwaters.org/events/?ical=1
