defaults:
  timezone: America/Chicago

sources:
  - name: Vilas County (Modern Tribe)
    url: https://vilaswi.com/events/?eventDisplay=list
    kind: modern_tribe

  - name: Boulder Junction (Modern Tribe)
    url: https://boulderjct.org/events/?eventDisplay=list
    kind: modern_tribe

  - name: Eagle River Chamber (Modern Tribe)
    url: https://eagleriver.org/events/?eventDisplay=list
    kind: modern_tribe

  - name: Rhinelander Chamber (GrowthZone)
    url: https://business.rhinelanderchamber.com/events/calendar
    kind: growthzone

  - name: Town of Arbor Vitae (Municipal Calendar)
    url: https://www.townofarborvitae.org/calendar/
    kind: modern_tribe   # many municipal WP sites also embed JSON-LD; this will pick it up

  - name: Minocqua Area Chamber (Simpleview)
    url: https://www.minocqua.org/events/
    kind: simpleview

  - name: Oneida County – Festivals & Events (Simpleview)
    url: https://oneidacountywi.com/festivals-events/
    kind: simpleview

  - name: St. Germain Chamber (Modern Tribe)
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    kind: modern_tribe

  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    url: https://sayner-starlake-cloverland.org/events/
    kind: modern_tribe
