defaults:
  tzname: America/Chicago
  default_duration_minutes: 120
  wait_ms: 4000

sources:
  - name: Vilas County (Modern Tribe)
    url: https://vilaswi.com/events/?eventDisplay=list
    kind: modern_tribe
    wait_selector: ".tribe-events, #tribe-events"

  - name: Boulder Junction (Modern Tribe)
    url: https://boulderjct.org/events/?eventDisplay=list
    kind: modern_tribe
    wait_selector: ".tribe-events, #tribe-events"

  - name: Eagle River Chamber (Modern Tribe)
    url: https://eagleriver.org/events/?eventDisplay=list
    kind: modern_tribe
    wait_selector: ".tribe-events, #tribe-events"

  - name: St. Germain Chamber (Micronet AJAX)
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    kind: st_germain_ajax
    wait_selector: "#mn-event-list, .eventList, .eventlist"

  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    url: https://sayner-starlake-cloverland.org/events/
    kind: modern_tribe
    wait_selector: ".tribe-events, #tribe-events"

  - name: Rhinelander Chamber (GrowthZone)
    url: https://business.rhinelanderchamber.com/events/calendar
    kind: growthzone
    wait_selector: "#calendar, .calendar, .gz-event-list"

  - name: Minocqua Area Chamber (Simpleview)
    url: https://www.minocqua.org/events/
    kind: simpleview
    wait_selector: ".event-list, .sv-list-view, #results"

  - name: Oneida County – Festivals & Events (Simpleview)
    url: https://oneidacountywi.com/festivals-events/
    kind: simpleview
    wait_selector: ".event-list, .sv-list-view, #results"

  - name: Town of Arbor Vitae (Municipal Calendar)
    url: https://www.townofarborvitae.org/calendar/
    kind: municipal
    wait_selector: ".events, .calendar, #tribe-events"
