defaults:
  tzname: America/Chicago
  default_duration_minutes: 120

sources:
  - name: Vilas County (Modern Tribe)
    url: https://vilaswi.com/events/?eventDisplay=list
    kind: modern_tribe
    fetch_live: true

  - name: Boulder Junction (Modern Tribe)
    url: https://boulderjct.org/events/?eventDisplay=list
    kind: modern_tribe
    fetch_live: true

  - name: Eagle River Chamber (Modern Tribe)
    url: https://eagleriver.org/events/?eventDisplay=list
    kind: modern_tribe
    fetch_live: true

  - name: Rhinelander Chamber (GrowthZone)
    url: https://business.rhinelanderchamber.com/events/calendar
    kind: growthzone
    fetch_live: true

  - name: Town of Arbor Vitae (Municipal Calendar)
    url: https://www.townofarborvitae.org/calendar/
    kind: modern_tribe   # they use TEC on WP; treat as modern_tribe
    fetch_live: true

  - name: Minocqua Area Chamber (Simpleview)
    url: https://www.minocqua.org/events/
    kind: simpleview
    fetch_live: true

  - name: Oneida County – Festivals & Events (Simpleview)
    url: https://oneidacountywi.com/festivals-events/
    kind: simpleview
    fetch_live: true

  - name: St. Germain Chamber (Modern Tribe)
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    kind: modern_tribe
    fetch_live: true

  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    url: https://sayner-starlake-cloverland.org/events/
    kind: modern_tribe
    fetch_live: true
