# Where to read sources from; this version aims for best-parsing backends per site.
defaults:
  tz: America/Chicago
  default_duration_minutes: 120

sources:
  - name: Vilas County (Modern Tribe)
    url: https://vilaswi.com/events/?eventDisplay=list
    kind: modern_tribe

  - name: Boulder Junction (Modern Tribe)
    url: https://boulderjct.org/events/?eventDisplay=list
    kind: modern_tribe

  - name: Eagle River Chamber (Modern Tribe)
    url: https://eagleriver.org/events/?eventDisplay=list
    kind: modern_tribe

  # GrowthZone can be JS-heavy; JSON-LD/SSR fallback in parser will try its best.
  - name: Rhinelander Chamber (GrowthZone)
    url: https://business.rhinelanderchamber.com/events/calendar
    kind: growthzone

  # Municipal calendar (WordPress) – ignore “Google Calendar” export links
  - name: Town of Arbor Vitae (Municipal Calendar)
    url: https://www.townofarborvitae.org/calendar/
    kind: municipal_calendar

  # Minocqua & Oneida run on Simpleview; JSON-LD first, strict fallbacks.
  - name: Minocqua Area Chamber (Simpleview)
    url: https://www.minocqua.org/events/
    kind: simpleview

  - name: Oneida County – Festivals & Events (Simpleview)
    url: https://oneidacountywi.com/festivals-events/
    kind: simpleview

  # St. Germain Modern Tribe (REST blocked often) – use HTML with JSON-LD.
  - name: St. Germain Chamber (Modern Tribe)
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    kind: modern_tribe

  # Sayner: prefer Modern Tribe HTML over ICS due to sporadic ICS blocks.
  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    url: https://sayner-starlake-cloverland.org/events/
    kind: modern_tribe
