# sources.yml — minimal keys, no anchors
sources:
  - name: Boulder Junction (Modern Tribe)
    kind: modern_tribe
    url: https://boulderjct.org/events/?eventDisplay=list
    tzname: America/Chicago

  - name: Eagle River Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://eagleriver.org/events/?eventDisplay=list
    tzname: America/Chicago

  - name: Minocqua Area Chamber (Simpleview)
    kind: simpleview
    url: https://www.minocqua.org/events/
    tzname: America/Chicago

  - name: Oneida County – Festivals & Events (Modern Tribe)
    kind: modern_tribe
    url: https://oneidacountywi.com/festivals-events/?eventDisplay=list
    tzname: America/Chicago

  - name: Presque Isle Chamber (ICS)
    kind: ics
    url: https://calendar.google.com/calendar/ical/presqueisle.chamber%40gmail.com/public/basic.ics
    tzname: America/Chicago

  - name: Rhinelander Chamber (GrowthZone)
    kind: growthzone
    url: https://business.rhinelanderchamber.com/events/calendar
    tzname: America/Chicago

  - name: Sayner–Star Lake–Cloverland Chamber (ICS)
    kind: ics
    url: https://calendar.google.com/calendar/ical/3l01djb44oouaq81l3rb8rm93o%40group.calendar.google.com/public/basic.ics
    tzname: America/Chicago

  - name: St. Germain Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    tzname: America/Chicago

  - name: Vilas County (Modern Tribe)
    kind: modern_tribe
    url: https://vilaswi.com/events/?eventDisplay=list
    tzname: America/Chicago
