defaults:
  tzname: "America/Chicago"
  default_duration_minutes: 120

sources:
  - name: "Vilas County (Modern Tribe)"
    url: "https://vilaswi.com/events/?eventDisplay=list"
    kind: "modern_tribe"
    wait_for_selectors:
      - "article.tribe-events-calendar-list__event"
      - ".tribe-events-calendar-list__event"

  - name: "Boulder Junction (Modern Tribe)"
    url: "https://boulderjct.org/events/?eventDisplay=list"
    kind: "modern_tribe"
    wait_for_selectors:
      - "article.tribe-events-calendar-list__event"
      - ".tribe-events-calendar-list__event"

  - name: "Eagle River Chamber (Modern Tribe)"
    url: "https://eagleriver.org/events/?eventDisplay=list"
    kind: "modern_tribe"
    wait_for_selectors:
      - "article.tribe-events-calendar-list__event"
      - ".tribe-events-calendar-list__event"

  - name: "St. Germain Chamber (Micronet AJAX)"
    url: "https://st-germain.com/events-calendar/?eventDisplay=list"
    kind: "st_germain_ajax"
    wait_for_selectors:
      - ".cm-event-list"
      - ".event-list"
      - ".eventItem"
      - ".event"        # broad fallback
    wait_timeout_ms: 45000

  - name: "Sayner–Star Lake–Cloverland Chamber (Modern Tribe)"
    url: "https://sayner-starlake-cloverland.org/events/"
    kind: "modern_tribe"
    wait_for_selectors:
      - "article.tribe-events-calendar-list__event"
      - ".tribe-events-calendar-list__event"

  - name: "Rhinelander Chamber (GrowthZone)"
    url: "https://business.rhinelanderchamber.com/events/calendar"
    kind: "growthzone"
    wait_for_selectors:
      - ".event-list"
      - ".eventItem"
      - ".event"        # broad fallback
    wait_timeout_ms: 45000

  - name: "Minocqua Area Chamber (Simpleview)"
    url: "https://www.minocqua.org/events/"
    kind: "simpleview"
    wait_for_selectors:
      - ".event-card"
      - ".event-list"
      - ".event"        # broad fallback

  - name: "Oneida County – Festivals & Events (Simpleview)"
    url: "https://oneidacountywi.com/festivals-events/"
    kind: "simpleview"
    wait_for_selectors:
      - ".event-card"
      - ".event-list"
      - ".event"        # broad fallback

  - name: "Town of Arbor Vitae (Municipal Calendar)"
    url: "https://www.townofarborvitae.org/calendar/"
    kind: "municipal"
    wait_for_selectors:
      - ".calendar"
      - ".events"
      - ".event"        # broad fallback
    wait_timeout_ms: 45000

  - name: "Town of Arbor Vitae (Squarespace)"
    url: "https://www.townofarborvitae.org/calendar/"
    kind: "squarespace"
    wait_for_selectors:
      - ".eventlist"
      - ".eventlist-event--upcoming"
      - "[data-collection-type='events']"
    wait_timeout_ms: 45000
