timezone: America/Chicago
default_duration_minutes: 60

sources:
  # Existing working scrapers
  - name: Vilas County (Modern Tribe)
    type: modern_tribe
    url: "https://vilaswi.com/events/?eventDisplay=list"

  - name: Boulder Junction (Modern Tribe)
    type: modern_tribe
    url: "https://boulderjct.org/events/?eventDisplay=list"

  # Switch these three back to HTML scraping + JS render fallback

  # Oneida County uses a Modern Tribe-style calendar but not a public ICS endpoint
  - name: Oneida County – Festivals & Events (Modern Tribe)
    type: modern_tribe
    url: "https://oneidacountywi.com/festivals-events/?eventDisplay=list"

  # Eagle River’s WordPress site runs The Events Calendar; parse the list view directly
  - name: Eagle River Chamber (Modern Tribe)
    type: modern_tribe
    url: "https://eagleriver.org/events/?eventDisplay=list"

  # Rhinelander is GrowthZone (ChamberMaster); render the calendar and parse cards/listings
  - name: Rhinelander Chamber (GrowthZone)
    type: growthzone
    url: "https://business.rhinelanderchamber.com/events/calendar"
    wait_selector: ".mn-calendar, .listing, .mn-event, .mn-event-card, .event"
