timezone: America/Chicago
default_duration_minutes: 60

sources:
  # HTML (Modern Tribe) — still fine to scrape with static/JS path
  - name: Vilas County (Modern Tribe)
    type: modern_tribe
    url: "https://vilaswi.com/events/?eventDisplay=list"

  - name: Boulder Junction (Modern Tribe)
    type: modern_tribe
    url: "https://boulderjct.org/events/?eventDisplay=list"

  # ICS (Modern Tribe sitewide ICS is more reliable than page-level ICS)
  - name: Oneida County – Festivals & Events (ICS)
    type: ics
    url: "https://oneidacountywi.com/events/?ical=1"
    ics_family: modern_tribe

  # ICS (GrowthZone native ICS avoids WP wrapper/403)
  - name: Eagle River Chamber (ICS)
    type: ics
    url: "https://business.eagleriver.org/events/ical?months=12"
    ics_family: growthzone

  - name: Rhinelander Chamber (ICS)
    type: ics
    url: "https://business.rhinelanderchamber.com/events/ical?months=12"
    ics_family: growthzone
