timezone: America/Chicago
default_duration_minutes: 60

sources:
  # --- Vilas County (Modern Tribe) ---
  - name: Vilas County (Modern Tribe)
    type: modern_tribe
    url: https://vilaswi.com/events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Boulder Junction (Modern Tribe) ---
  - name: Boulder Junction (Modern Tribe)
    type: modern_tribe
    url: https://boulderjct.org/events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Oneida County – Festivals & Events (Modern Tribe) ---
  - name: Oneida County – Festivals & Events (Modern Tribe)
    type: modern_tribe
    url: https://oneidacountywi.com/festivals-events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Eagle River Chamber (Modern Tribe) ---
  - name: Eagle River Chamber (Modern Tribe)
    type: modern_tribe
    url: https://eagleriver.org/events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Rhinelander Chamber (GrowthZone) ---
  - name: Rhinelander Chamber (GrowthZone)
    type: growthzone
    url: https://business.rhinelanderchamber.com/events/calendar
    wait_selector: ".mn-event, .mn-event-card, .event"

  # --- St. Germain Chamber (Modern Tribe) ---
  - name: St. Germain Chamber (Modern Tribe)
    type: modern_tribe
    url: https://st-germain.com/events-calendar/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Minocqua Area Chamber (Modern Tribe) ---
  - name: Minocqua Area Chamber (Modern Tribe)
    type: modern_tribe
    url: https://www.minocqua.org/events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Town of Arbor Vitae (Ai1EC) ---
  - name: Town of Arbor Vitae (Municipal Calendar)
    type: ai1ec
    url: https://www.townofarborvitae.org/calendar/
    wait_selector: ".ai1ec-event-instance, .ai1ec-agenda-event"

  # --- Sayner–Star Lake–Cloverland Chamber (Modern Tribe) ---
  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    type: modern_tribe
    url: https://sayner-starlake-cloverland.org/events/
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Manitowish Waters Chamber (Modern Tribe) ---
  - name: Manitowish Waters Chamber (Modern Tribe)
    type: modern_tribe
    url: https://manitowishwaters.org/events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"

  # --- Presque Isle Chamber (Modern Tribe) ---
  - name: Presque Isle Chamber (Modern Tribe)
    type: modern_tribe
    url: https://presqueisle.com/events/?eventDisplay=list
    wait_selector: ".tribe-events-calendar-list__event"
