timezone: America/Chicago
default_duration_minutes: 60

sources:
  - name: Vilas County (Modern Tribe)
    type: modern_tribe
    url: "https://vilaswi.com/events/?eventDisplay=list"

  - name: Boulder Junction (Modern Tribe)
    type: modern_tribe
    url: "https://boulderjct.org/events/?eventDisplay=list"

  # Use native ICS instead of scraping:
  - name: Oneida County – Festivals & Events (ICS)
    type: ics
    url: "https://oneidacountywi.com/festivals-events/?ical=1"

  # GrowthZone calendar is wrapped by WP, but site exposes Modern Tribe ICS.
  # Prefer the native ICS we saw advertised in your snapshot.
  - name: Eagle River Chamber (ICS)
    type: ics
    url: "https://eagleriver.org/events/?ical=1"

  # Keep GrowthZone for Rhinelander; use renderer and wait for a likely list selector.
  - name: Rhinelander Chamber (GrowthZone)
    type: growthzone
    url: "https://business.rhinelanderchamber.com/events/search"
    wait_selector: ".listing, .mn-event, .event"

