timezone: America/Chicago
default_duration_minutes: 60

sources:
  - name: Vilas County (Modern Tribe)
    type: modern_tribe
    url: "https://vilaswi.com/events/?eventDisplay=list"

  - name: Boulder Junction (Modern Tribe)
    type: modern_tribe
    url: "https://boulderjct.org/events/?eventDisplay=list"

  # These two are WP pages that often EMBED calendars in iframes.
  - name: Oneida County – Festivals & Events (Modern Tribe)
    type: modern_tribe
    url: "https://oneidacountywi.com/festivals-events/?eventDisplay=list"

  - name: Eagle River Chamber (Modern Tribe)
    type: modern_tribe
    url: "https://eagleriver.org/events/?eventDisplay=list"

  # GrowthZone calendar (often JS/iframe only) — the iframe handling will kick in.
  - name: Rhinelander Chamber (GrowthZone)
    type: growthzone
    url: "https://business.rhinelanderchamber.com/events/calendar"
    wait_selector: ".mn-calendar, .listing, .mn-event, .mn-event-card, .event"
