# Consolidated sources list for Northwoods Events

# --- Modern Tribe (HTML list only; REST often blocked) ---
- name: Vilas County (Modern Tribe)
  type: modern_tribe
  url: https://vilaswi.com/events/?eventDisplay=list

- name: Boulder Junction (Modern Tribe)
  type: modern_tribe
  url: https://boulderjct.org/events/?eventDisplay=list

- name: Oneida County – Festivals & Events (Modern Tribe)
  type: modern_tribe
  url: https://oneidacountywi.com/festivals-events/?eventDisplay=list

- name: Eagle River Chamber (Modern Tribe)
  type: modern_tribe
  url: https://eagleriver.org/events/?eventDisplay=list

- name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
  type: modern_tribe
  url: https://sayner-starlake-cloverland.org/events/?eventDisplay=list

- name: Presque Isle Chamber (Modern Tribe)
  type: modern_tribe
  url: https://presqueisle.com/events/?eventDisplay=list

- name: Manitowish Waters Chamber (Modern Tribe)
  type: modern_tribe
  url: https://manitowishwaters.org/events/?eventDisplay=list

# --- GrowthZone (Micronet) ---
- name: Rhinelander Chamber (GrowthZone)
  type: growthzone
  url: https://business.rhinelanderchamber.com/events/calendar

- name: St. Germain Chamber (GrowthZone)
  type: growthzone
  url: https://st-germain.com/events-calendar/

# --- Simpleview (Minocqua) ---
- name: Minocqua Area Chamber (Simpleview)
  type: simpleview
  url: https://www.minocqua.org/events

# --- Squarespace (Arbor Vitae) ---
- name: Town of Arbor Vitae (Squarespace Calendar)
  type: squarespace
  url: https://www.townofarborvitae.org/calendar/

# --- Optional: ICS endpoints (only if known to return real ICS) ---
# Keep disabled by default—many of these return HTML when bot-detected.
# - name: Minocqua Area Chamber (ICS)
#   type: ics
#   url: https://www.minocqua.org/events/?ical=1
#   enabled: false
#
# - name: St. Germain Chamber (ICS)
#   type: ics
#   url: https://st-germain.com/events-calendar/?ical=1
#   enabled: false
#
# - name: Town of Arbor Vitae (ICS)
#   type: ics
#   url: https://www.townofarborvitae.org/calendar/?ical=1
#   enabled: false
