# What: master list of sources to crawl
# Notes:
# - kind controls which parser path runs
# - tz is optional; defaults to America/Chicago in code
# - ics_fallback: if true, we’ll try ?ical=1 when primary fails
# - default_duration_minutes: used only when no end time is available

defaults:
  tz: America/Chicago
  ics_fallback: true
  default_duration_minutes: 120

sources:
  - name: Vilas County (Modern Tribe)
    kind: modern_tribe
    url: https://vilaswi.com/events/?eventDisplay=list

  - name: Boulder Junction (Modern Tribe)
    kind: modern_tribe
    url: https://boulderjct.org/events/?eventDisplay=list

  - name: Oneida County – Festivals & Events (Modern Tribe)
    kind: modern_tribe
    url: https://oneidacountywi.com/festivals-events/?eventDisplay=list

  - name: Eagle River Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://eagleriver.org/events/?eventDisplay=list

  - name: Rhinelander Chamber (GrowthZone)
    kind: growthzone
    url: https://business.rhinelanderchamber.com/events/calendar

  - name: St. Germain Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://st-germain.com/events-calendar/?eventDisplay=list

  - name: Minocqua Area Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://www.minocqua.org/events/?eventDisplay=list

  - name: Town of Arbor Vitae (Municipal Calendar)
    kind: municipal_calendar
    url: https://www.townofarborvitae.org/calendar/

  - name: Sayner–Star Lake–Cloverland Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://sayner-starlake-cloverland.org/events/

  - name: Manitowish Waters Chamber (Modern Tribe)
    kind: modern_tribe
    url: https://manitowishwaters.org/events/?eventDisplay=list
