name: Build Northwoods ICS

on:
  schedule:
    - cron: "15 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build ICS
        run: |
          python main.py --out build/events.ics --report build/last_run_report.json
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build/events.ics build/last_run_report.json
          git commit -m "Update ICS ($(date -u +%Y-%m-%dT%H:%M:%SZ))" || echo "No changes"
          git push
