name: Build ICS and Deploy Pages

on:
  schedule:
    - cron: '15 9 * * *'  # daily at 09:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - run: bash -lc 'rm -rf public && mkdir -p public && printf "%s\n" "<!doctype html>" "<meta charset=\"utf-8\">" "<h1>OK</h1>" > public/index.html'

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
