# .github/workflows/scrape.yml (example name)
name: Scrape & Parse Events

on:
  schedule:
    - cron: "15 * * * *"   # hourly, adjust as you like
  workflow_dispatch:

permissions:
  contents: write   # needed only if you enable the commit step below

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper
        run: |
          set -euo pipefail
          python src/main.py > /dev/null
          # ensure report is where we expect:
          test -f state/last_run_report.json

      - name: Upload last_run_report artifact
        uses: actions/upload-artifact@v4
        with:
          name: last_run_report
          path: state/last_run_report.json
          if-no-files-found: error

      # (Optional) Also commit the file to the repo,
      # so manual builds always have a fresh copy without needing artifacts.
      - name: Commit updated last_run_report.json (optional)
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state/last_run_report.json
          git commit -m "chore: update last_run_report.json [skip ci]" || echo "No changes to commit"
          git push
