name: Build & Deploy Pages

on:
  workflow_run:
    workflows: ["Scrape & Parse Events"]
    types: [completed]

permissions:
  contents: read      # to checkout/read the repo
  pages: write        # to upload & publish the Pages artifact
  id-token: write     # for OIDC auth used by actions/deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
