name: Build and Deploy Pages

on:
  workflow_run:
    workflows: ["Scrape & Parse Events"]
    types: [completed]
  workflow_dispatch:

# Avoid overlapping deployments
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If the scrape workflow uploaded artifacts, pull them in
      - name: Download artifacts from scrape run (if present)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          path: downloaded
          if_no_artifact_found: ignore

      - name: Build static site
        run: |
          set -euo pipefail
          mkdir -p public/state

          # Prefer an artifact copy of last_run_report.json if one exists
          ART_JSON="$(find downloaded -name last_run_report.json -print -quit || true)"
          if [ -n "${ART_JSON:-}" ]; then
            echo "Found artifact: ${ART_JSON}"
            cp "${ART_JSON}" public/state/last_run_report.json
          elif [ -f state/last_run_report.json ]; then
            echo "Found repo file: state/last_run_report.json"
            cp state/last_run_report.json public/state/last_run_report.json
          else
            echo "No last_run_report.json found."
          fi

          # Minimal index.html so the site isn't empty
          BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          cat > public/index.html <<'HTML'
<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Northwoods Events</title>
<style>
  body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; margin: 2rem; }
  code { background:#f6f8fa; padding:.1rem .3rem; border-radius:.25rem; }
</style>
<h1>Northwoods Events</h1>
<p>This site publishes the latest scrape report, if available.</p>
<p>Built: <code>__BUILD_TIME__</code></p>
<p><a href="./state/last_run_report.json">Download last_run_report.json</a></p>
HTML
          # inject build time
          sed -i "s#__BUILD_TIME__#${BUILD_TIME}#g" public/index.html

      - name: Show output tree (debug)
        run: |
          echo "---- repo root ----"; ls -lah || true
          echo "---- downloaded (if any) ----"; ls -lah downloaded || true
          echo "---- public ----"; ls -lah public || true
          echo "---- public/state ----"; ls -lah public/state || true

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
