name: Build unified ICS

on:
  schedule:
    - cron: "5 * * * *"   # runs hourly (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper + build ICS
        run: |
          python src/main.py

      - name: Commit updates (state + ICS)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state/ docs/northwoods.ics
          git commit -m "Update ICS ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || echo "No changes"
          git push
