name: Build ICS and Deploy Pages

on:
  schedule:
    - cron: '15 9 * * *'  # daily at 09:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python & install deps
        run: |
          set -euo pipefail
          python -V
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 lxml ics python-dateutil pytz pyyaml
          fi
          echo "---- pip freeze (first 200 lines) ----"
          pip freeze | sed -n '1,200p'

      - name: Run builder and collect artifacts
        env:
          TZ: America/Chicago
        run: |
          set -euo pipefail
          rm -rf public
          mkdir -p public

          {
            echo "===== BUILD START $(date -u +'%Y-%m-%dT%H:%M:%SZ') ====="
            echo "CWD: $(pwd)"
            echo "PYTHON: $(python -V)"
            echo "-------------------------------------------"
            ls -la
            echo "-------------------------------------------"
            if [ -f src/main.py ]; then
              echo "Running: python src/main.py"
              python src/main.py
            else
              echo "::error::No src/main.py found."
              exit 2
            fi
            echo "-------------------------------------------"
            echo "Repo root after build:"
            ls -la
            echo "-------------------------------------------"
            if [ -d state ]; then
              echo "state/ (top 200 files):"
              find state -type f | sed -n '1,200p'
            else
              echo "NOTE: No state/ directory produced."
            fi
            echo "===== BUILD END $(date -u +'%Y-%m-%dT%H:%M:%SZ') ====="
          } 2>&1 | tee public/build.log

          # Surface ICS from src/ to root if needed
          if [ -f src/northwoods.ics ] && [ ! -f northwoods.ics ]; then
            cp src/northwoods.ics ./northwoods.ics
          fi

          # Prepare public site
          mkdir -p public/state
          if [ -d state ]; then
            cp -a state/. public/state/
          fi
          if [ -f northwoods.ics ]; then
            cp northwoods.ics public/
          fi

          # Index
          {
            echo '<!doctype html>'
            echo '<meta charset="utf-8">'
            echo '<title>Northwoods Events - Artifacts</title>'
            echo '<h1>Northwoods Events - Artifacts</h1>'
            echo '<ul>'
            [ -f public/northwoods.ics ] && echo '  <li><a href="northwoods.ics">northwoods.ics</a></li>'
            [ -d public/state ] && echo '  <li><a href="state/">state/ (snapshots, last_run_report.json)</a></li>'
            echo '  <li><a href="build.log">build.log (full console output)</a></li>'
            echo '</ul>'
            echo '<hr><p>Auto-published by GitHub Actions.</p>'
          } > public/index.html

          echo "Public artifact contents (top):"
          find public -maxdepth 3 -type f | sed -n '1,200p'

          # Fail if nothing meaningful was produced
          if [ ! -f public/northwoods.ics ] && [ ! -d public/state ]; then
            echo "::error::No northwoods.ics and no state/ produced. See build.log."
            exit 1
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (github-pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
