name: "Build ICS & Deploy Pages"

on:
  schedule:
    - cron: "15 9 * * *"   # daily at 09:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  PYTHON_VERSION: "3.11"

jobs:
  build:
    name: "Build ICS & prepare site"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Install dependencies"
        run: bash -eo pipefail -c "python -m pip install --upgrade pip && if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests beautifulsoup4 lxml ics python-dateutil pytz pyyaml; fi"

      - name: "Show sources file(s) found"
        run: bash -eo pipefail -c "echo 'Looking for sources.{yaml,yml} at repo root and in src/...'; found=0; for p in sources.yaml sources.yml src/sources.yaml src/sources.yml; do if [ -f \"$p\" ]; then echo \" - found: $p\"; found=1; fi; done; if [ $found -eq 0 ]; then echo '::warning::No sources.yaml/yml found at repo root or in src/.'; fi"

      - name: "Run builder (src/main.py)"
        env:
          TZ: America/Chicago
        run: bash -eo pipefail -c "echo 'Running: python src/main.py'; python src/main.py; echo; echo 'Outputs at repo root:'; ls -la || true; echo; if [ -d state ]; then echo 'state/ (top 200 files):'; find state -type f | sed -n '1,200p'; else echo '::warning::No state/ dir produced.'; fi; if [ -f src/northwoods.ics ] && [ ! -f northwoods.ics ]; then cp src/northwoods.ics ./northwoods.ics; fi; if [ -f northwoods.ics ]; then echo 'northwoods.ics present at repo root.'; else echo '::warning::northwoods.ics not found.'; fi"

      - name: "Commit & push changes (if any)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash -eo pipefail -c "git config user.name 'github-actions[bot]'; git config user.email 'github-actions[bot]@users.noreply.github.com'; git add -A; if git diff --cached --quiet; then echo 'No changes to comm
