name: Daily ICS build + email

on:
  schedule:
    # 8:00 AM America/Chicago (~13:00 UTC during CDT)
    - cron: "0 13 * * *"
  workflow_dispatch:
    inputs:
      send_test_email:
        description: "Force a test email (creates a dummy digest if none exists)"
        required: true
        default: "false"
      test_to:
        description: "Override TO address (optional)"
        required: false
        default: ""
      test_note:
        description: "Optional note to include in the test email"
        required: true
        default: "test email"

jobs:
  build_and_email:
    runs-on: ubuntu-latest
    env:
      TZ: America/Chicago

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If your scraper uses Playwright for JS rendering:
          python -m playwright install --with-deps chromium

      - name: Build ICS and digest
        run: python src/main.py

      - name: Show new items (optional)
        run: |
          if [ -f state/new_items.json ]; then
            echo "New items:"
            cat state/new_items.json
          else
            echo "No new items produced by main.py."
          fi

      - name: Check for digest file
        id: has_digest
        run: |
          if [ -f state/daily_digest.txt ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      # If manually triggered with send_test_email=true and no digest exists,
      # create a simple test digest so an email is always sent.
      - name: Create test digest if requested
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.send_test_email == 'true' && steps.has_digest.outputs.present == 'false' }}
        run: |
          mkdir -p state
          NOW_CHI=$(date +"%Y-%m-%d (%a) %I:%M %p %Z")
          TODAY=$(date +"%Y-%m-%d")
          NOTE="${{ github.event.inputs.test_note }}"

          cat > state/daily_digest.txt <<EOF
New Northwoods Events added today:

$TODAY
  Source: Test Harness
    • Example Event @ Anywhere, WI
      $NOW_CHI - $NOW_CHI
      https://dsundt.github.io/northwoods-events/northwoods.ics

Note: $NOTE
EOF

          cat > state/daily_digest.html <<EOF
<h2>New Northwoods Events added today</h2>
<h3>$TODAY</h3>
<ul>
  <li><strong>Source:</strong> Test Harness
    <ul>
      <li>
        <div><strong>Example Event</strong> @ Anywhere, WI</div>
        <div>$NOW_CHI - $NOW_CHI</div>
        <div><a href="https://dsundt.github.io/northwoods-events/northwoods.ics">https://dsundt.github.io/northwoods-events/northwoods.ics</a></div>
      </li>
    </ul>
  </li>
</ul>
<p><em>$NOTE</em></p>
EOF

          NOW_Z=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > state/new_items.json <<EOF
[
  {
    "title": "Example Event",
    "start": "$NOW_Z",
    "end": "$NOW_Z",
    "location": "Anywhere, WI",
    "url": "https://dsundt.github.io/northwoods-events/northwoods.ics",
    "source": "Test Harness",
    "all_day": false
  }
]
EOF

      - name: Commit updated ICS & state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/northwoods.ics state/*.json state/*.txt state/*.html || true
          git diff --cached --quiet || git commit -m "Daily update: ICS + state"
          git push || true

      - name: Load HTML body
        id: load_html
        run: |
          if [ -f state/daily_digest.html ]; then
            BODY="$(cat state/daily_digest.html)"
          elif [ -f state/daily_digest.txt ]; then
            ESCAPED="$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' state/daily_digest.txt)"
            BODY="<pre>${ESCAPED}</pre>"
          else
            BODY="<p>No new items.</p>"
          fi
          echo 'body<<EOF' >> "$GITHUB_OUTPUT"
          echo "$BODY" >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

      - name: Resolve recipient
        id: rcpt
        run: |
          if [ -n "${{ github.event.inputs.test_to }}" ]; then
            echo "to=${{ github.event.inputs.test_to }}" >> "$GITHUB_OUTPUT"
          else
            echo "to=${{ secrets.MAIL_TO }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Send email digest
        # Send if we have any digest file (real or test)
        if: ${{ hashFiles('state/daily_digest.txt') != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Northwoods Events - New items
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ steps.rcpt.outputs.to }}
          html_body: ${{ steps.load_html.outputs.body }}
          attachments: |
            state/new_items.json
