name: Northwoods Events (ICS + Daily Email)

on:
  # Hourly build to keep the ICS fresh
  schedule:
    - cron: "0 * * * *"        # every hour (UTC)
    # Daily email at 08:00 America/Chicago (13:00 UTC during CDT)
    - cron: "0 13 * * *"
  # Manual run with toggles
  workflow_dispatch:
    inputs:
      run_build:
        description: "Run ICS build step"
        type: boolean
        default: true
      run_email:
        description: "Send daily email"
        type: boolean
        default: false

permissions:
  contents: write   # needed to push updated ICS/state back to the repo

env:
  PYTHON_VERSION: "3.11"

jobs:

  build_ics:
    # Run on all hourly triggers, and also on the 13:00 UTC daily tick.
    # Also run when manually requested via workflow_dispatch.
    if: >
      (github.event_name == 'schedule' && (github.event.schedule == '0 * * * *' || github.event.schedule == '0 13 * * *'))
      || (github.event_name == 'workflow_dispatch' && (inputs.run_build == 'true' || inputs.run_build == true))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (force fresh)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found; installing core libs"
            pip install requests beautifulsoup4 lxml ics pyyaml pytz python-dateutil
          fi

      - name: Build ICS & state
        run: |
          set -e
          python src/main.py
          echo "Done building ICS and state."

      - name: Commit and push changes (if any)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add everything new/changed (ics & state)
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update: ICS + state"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
            echo "Pushed changes."
          fi

  daily_email:
    # Send email only on the 13:00 UTC schedule tick, or when manually requested.
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '0 13 * * *')
      || (github.event_name == 'workflow_dispatch' && (inputs.run_email == 'true' || inputs.run_email == true))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (force fresh)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Ensure digest files exist (fallback)
        run: |
          # If your main.py already generates these daily, great.
          # This fallback creates minimal files so the mail step won't fail.
          mkdir -p state
          if [ ! -f state/daily_digest.txt ]; then
            echo "No new items today." > state/daily_digest.txt
          fi
          if [ ! -f state/daily_digest.html ]; then
            printf "<html><body><p>No new items today.</p></body></html>\n" > state/daily_digest.html
          fi

      - name: Send daily email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Northwoods Events: New Items Digest"
          from: "Northwoods Bot <${{ secrets.SMTP_FROM }}>"
          to: ${{ secrets.SMTP_TO }}
          # Prefer HTML if available
          html_body: file://state/daily_digest.html
          # Also attach the ICS file (so you can import quickly if desired)
          attachments: |
            docs/northwoods.ics
