name: Scrape & Parse Events

on:
  workflow_dispatch:
  schedule:
    - cron: "7 */3 * * *"  # every 3 hours at minute 7

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ REQUIRED for Playwright to launch Chromium on the runner
      - name: Install Playwright browsers (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          # Let parsers know they can use a real browser
          USE_PLAYWRIGHT: "1"
        run: |
          set -euo pipefail
          python src/main.py < sources.yml

      # Optional: upload artifacts for the deploy workflow
      - name: Upload scrape artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scrape-output
          path: |
            state/last_run_report.json
            northwoods*.ics
            state/snapshots/**
