name: Build ICS and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      USE_PLAYWRIGHT: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install Playwright Chromium (with system deps)
        run: python -m playwright install --with-deps chromium

      - name: Ensure src package exists
        run: test -f src/__init__.py || printf "" > src/__init__.py

      - name: Run scraper
        run: python -m src.main

      - name: Create public folders
        run: mkdir -p public/state public/ics

      - name: Stage reports to public
        run: cp -f state/last_run_report.json public/state/last_run_report.json || true

      - name: Stage events to
