name: Scrape, Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    env:
      USE_PLAYWRIGHT: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Ensure package init
        run: test -f src/__init__.py || printf "" > src/__init__.py

      - name: Verify helper scripts exist
        run: |
          test -f .github/scripts/extract_sources.py || (echo "Missing .github/scripts/extract_sources.py" && exit 1)
          test -f .github/scripts/verify_freshness.py || (echo "Missing .github/scripts/verify_freshness.py" && exit 1)

      - name: Clean state/output
        run: |
          rm -rf state northwoods.ics public
          mkdir -p state public/state public/ics

      - name: Extract sources -> .tmp.sources.yaml
        run: python .github/scripts/extract_sources.py

      - name: Scrape
        run: python -m src.main < .tmp.sources.yaml

      - name: Verify freshness (must be today)
        run: python .github/scripts/verify_freshness.py

      - name: Stage site files
        run: |
          cp -f state/last_run_report.json public/state/last_run_report.json
          cp -f state/events.json public/state/events.json
          test -f northwoods.ics && cp -f northwoods.ics public/ics/northwoods.ics || true
          ls -la public public/state public/ics || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
          name: github-pages
          retention-days: 1

      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: state-debug
          path: |
            state
            northwoods.ics
            .tmp.sources.yaml

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
