name: Build ICS & Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Ensure package init
        run: test -f src/__init__.py || printf "" > src/__init__.py

      - name: Run scraper
        env:
          USE_PLAYWRIGHT: "1"
        run: python -m src.main

      - name: Stage site files
        run: |
          mkdir -p public/state public/ics
          cp -f state/last_run_report.json public/state/last_run_report.json || true
          cp -f state/events.json public/state/events.json || true
          cp -f northwoods.ics public/ics/northwoods.ics || true
          if [ ! -f public/index.html ]; then
            echo '<!doctype html><meta charset="utf-8"><title>Northwoods Events</title><h1>Artifacts</h1><ul><li><a href="state/last_run_report.json">last_run_report.json</a></li><li><a href="state/events.json">events.json</a></li><li><a href="ics/northwoods.ics">northwoods.ics</a></li></ul>' > public/index.html
          fi
          if [ ! -f public/.nojekyll ]; then
            : > public/.nojekyll
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
          name: github-pages
          retention-days: 1

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
