name: Build ICS & Deploy Pages

on:
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: python -m playwright install --with-deps chromium

      - name: Ensure src package
        run: test -f src/__init__.py || printf "" > src/__init__.py

      - name: Scrape and build ICS
        env:
          USE_PLAYWRIGHT: "1"
        run: python -m src.main

      - name: Verify outputs exist
        run: test -s state/last_run_report.json

      - name: Stage outputs for Pages (dirs)
        run: mkdir -p public/state public/ics

      - name: Stage outputs for Pages (files)
        run: cp -f state/last_run_report.json public/state/last_run_report.json

      - name: Stage optional events.json
        run: cp -f state/events.json public/state/events.json || true

      - name: Stage ICS
        run: cp -f northwoods.ics public/ics/northwoods.ics || true

      - name: Write minimal index.html
        run: echo '<!doctype html><meta charset="utf-8"><title>Northwoods Events</title><h1>Artifacts</h1><ul><li><a href="state/last_run_report.json">last_run_report.json</a></li><li><a href="state/events.json">events.json</a></li><li><a href="ics/northwoods.ics">northwoods.ics</a></li></ul>' > public/index.html

      - name: Commit outputs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state northwoods.ics
          git commit -m "data: update state and ICS [skip ci]" || echo "no changes"
          git push

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
